---
- name: Deploy cron script
  template:
    src: 'restic.cron.j2'
    dest: '/etc/cron.d/restic-{{ item.name }}'
    mode: '0640'
  no_log: true
  with_items: '{{ restic_repos }}'
  register: cronfiles

- name: Initialize restic repositories
  command: "{{ restic_install_path }}/restic -r {{ item.url }} init"
  environment: 
    RESTIC_PASSWORD: "{{ item.password }}"
  no_log: true
  with_items: "{{ restic_repos }}"
  when:
    - cronfiles is changed
    - ci_testing is undefined
